routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/','WelcomeController@index');
Route::get('about','WelcomeController@about');
Route::resource('issues', 'IssuesController');

Route::resource('comments', 'CommentsController', ['only' => 'store']);
Route::resource('photos', 'PhotosController', ['only' => 'store']);
Auth::routes();

//Route::get('/home', 'HomeController@index')->name('home');

Route::group(['prefix'=>'auth/github','namespace'=>'Auth'],function(){
    Route::get('/', 'SocialitesController@github');
    Route::get('callback', 'SocialitesController@callback');
});

app/Models/Comment.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Comment extends Model
{
    protected $fillable = ['issue_id','content','user_id'];

    public function issue(){
        return $this->belongsTo('App\Models\Issue');
    }

    //每条评论，都是属于一个用户
    public function user(){
        return $this->belongsTo('App\User');
    }
}

app/Models/Issue.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Issue extends Model
{
    protected $fillable = ['title','content','user_id'];
    public function comments(){
        return $this->hasMany('App\Models\Comment');
    }
    // 每一个issue，都属于一个user
    public function user()
    {
        return $this->belongsTo('App\User');
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use App\Notifications\ResetPasswordNotification;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password','username','provider', 'uid', 'avatar'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /**
     * 发送邮件
     * @param string $token
     */
    public function sendPasswordResetNotification($token)
    {
        $this->notify(new ResetPasswordNotification($token));
    }
    // 一个user 有很多 issues。
    public function issues()
    {
        return $this->hasMany('App\Models\Issue');
    }
    /**
     * 用户头像
     * @return mixed|string
     */
    public function avatar()
    {
        return $this->avatar ? $this->avatar : "https://www.gravatar.com/avatar/" . md5(strtolower($this->email)) . "?d=retro&s=48";
    }
    // 一个 user有很多 comments
    public function comments()
    {
        return $this->hasMany('App\Models\Comment');
    }
}

app/Http/Controllers/CommentsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Comment;

class CommentsController extends Controller
{
    public function store(Request $request)
    {
        $comment = Comment::create($request->all());
        return view('shared._comment', compact('comment'));
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/IssuesController.php
<?php

namespace App\Http\Controllers;

use App\Models\Issue;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\Http\Requests\StoreIssue, App\Http\Requests\UpdateIssue;

class IssuesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $issues = Issue::with('user','comments')->orderBy('created_at','desc')->paginate(5);
        return view('issues.index')->with('issues',$issues);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if(!Auth::check()){
            return redirect('/')->with('alert','没有执行此操作的权限，请先登录');
        }
        return view('issues.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreIssue $request)
    {
        Issue::create($request->all());
        return redirect('/')->with('notice', 'Issue 新增成功~');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Issue $issue)
    {
        $comments = $issue->comments()->with('user')->get();
        return view('issues.show', compact('issue', 'comments'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Issue $issue)
    {
        //$issue = Issue::find($id);
        return view('issues.edit',['issue'=>$issue]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateIssue $request, Issue $issue)
    {
        //$issue = Issue::find($id);
        $issue = $issue->update($request->all());
        return redirect(route('issues.show',$issue->id));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Issue $issue)
    {
        //Issue::destroy($id);
        $issue->delete();
        return redirect('/')->with('alert', 'Issue 删除成功~');
    }
}

app/Http/Controllers/PhotosController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class PhotosController extends Controller
{
    public function store(Request $request)
    {
        if (!$request->hasFile('file')) {
            return response()->json(['message' => '没有上传文件'], 422);
        }

        if (!$request->file->isValid()) {
            return response()->json(['message' => '文件上传过程中出错了'], 422);
        }

        //上传格式验证
        $allow = ['image/jpeg', 'image/png', 'image/gif'];
        $type = $request->file->getMimeType();
        //return $type;

        if (!in_array($type, $allow)) {
            return response()->json(['message' => '文件类型错误，只能上传图片'], 422);
        }

        //文件大小验证
        $max_size = 1024 * 1024 * 2;
        $size = $request->file->getClientSize();
        //return $size;

        if ($size > $max_size) {
            return response()->json(['message' => '文件大小不能超过2M'], 422);
        }
        $path = $request->file->store('public/images');
        $url = \Storage::url($path);//真正可以访问到的图片地址
        return response()->json(['message' => 'success', 'data' => $url], 200);
    }
}

app/Http/Controllers/WelcomeController.php
<?php

namespace App\Http\Controllers;

use App\Models\Issue;
use Illuminate\Http\Request;

class WelcomeController extends Controller
{
    public function index(){
        $issues = Issue::with('user','comments')->orderBy('created_at','desc')->take(2)->get();
        return view('welcome.index')->with('issues',$issues);
    }
    public function about(){
        return view('welcome.about');
    }
}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/issues/_form.blade.php
{!! Form::hidden('user_id', Auth::id()) !!}
<fieldset>
    <div class="am-form-group">
        {{ Form::label('标题') }}
        {{ Form::text('title', null, ['placeholder' => '输入活动标题']) }}
    </div>

    <div class="am-form-group">
        {{ Form::label('内容') }}
        {{ Form::textarea('content', null,  ['rows' => '12', 'placeholder' => '填写活动内容，支持markdown。']) }}
    </div>

    {{ Form::submit('提交', ['class' => 'am-btn am-btn-default']) }}
</fieldset>

resources/views/issues/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="am-container">
        <div class="header">
            <div class="am-g">
                <h1>添加新活动</h1>
            </div>
            <hr>
        </div>


        {!! Form::open(['route' => 'issues.store', 'class' => 'am-form']) !!}
        @include('issues._form')
        {!! Form::close() !!}
    </div>
@endsection

resources/views/issues/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="am-container">
        <div class="header">
            <div class="am-g">
                <h1>编辑活动</h1>
            </div>
            <hr>
        </div>

        {!! Form::model($issue, ['route' => ['issues.update', $issue->id], 'method' => 'put', 'class' => 'am-form']) !!}
        @include('issues._form')
        {!! Form::close() !!}
    </div>
@endsection

resources/views/issues/index.blade.php
@extends('layouts.app')
@section('content')

    <div class="detail">
        <div class="am-g am-container">
            <div class="am-u-lg-12">
                <h1 class="detail-h1">所有的活动都在下面了...</h1>
            </div>
        </div>
    </div>

    @include('shared._issue_list')
    {{$issues->links()}}
@endsection

resources/views/issues/show.blade.php
@extends('layouts.app')
@section('stylesheets')
    <link rel="stylesheet" href="/assets/vendor/atwho/jquery.atwho.min.css">
    <link rel="stylesheet" href="/assets/vendor/highlight/default.min.css">
    <style>
        .am-comment-bd h2 {
            margin-top: 0;
            border-bottom: 1px solid #e6e8ec;
        }

        .am-comment-bd .hljs {
            background: none;
        }

        .am-comment-bd pre {
            border-radius: 5px;
        }
    </style>
@endsection
@section('content')

    <div class="issue-heading">
        <div class="am-container">
            {{$issue->title}}
            @if (Auth::check() && Auth::user() == $issue->user )
                <a href="{{route('issues.destroy', $issue->id)}}" data-method="delete" data-token="{{csrf_token()}}"
                   data-confirm="Are you sure?" type="button"
                   class="am-btn am-btn-danger am-radius am-btn-sm">Destroy</a>
                <a href="{{route('issues.edit', $issue->id)}}" type="button"
                   class="am-btn am-btn-primary am-radius am-btn-sm">Edit</a>
            @endif
        </div>
    </div>

    <div class="am-container">
        <ul class="am-comments-list am-comments-list-flip">

            <li class="am-comment">
                <img src="{{$issue->user->avatar()}}" alt="" class="am-comment-avatar" width="100" height="100">
                <div class="am-comment-main">
                    <header class="am-comment-hd">
                        <div class="am-comment-meta">
                            <span class="am-comment-author">{{$issue->user->name}}</span>
                        </div>
                    </header>
                    <div class="am-comment-bd"><p>{{$issue->content}}</p></div>
                </div>
            </li>

            @foreach($comments as $comment)

                <li class="am-comment">
                    <img src="{{$comment->user->avatar()}}" alt="" class="am-comment-avatar" width="48" height="48">

                    @include('shared._comment')
                </li>
            @endforeach
        </ul>
        @if (Auth::check())
            {!! Form::open(['route' => 'comments.store', 'class' => 'am-form']) !!}
            {!! Form::hidden('issue_id', $issue->id) !!}
            {!! Form::hidden('user_id', Auth::id()) !!}
            <fieldset>
                <div class="am-form-group">
                    {{ Form::textarea('content', null,  ['rows' => '5', 'placeholder' => '填写评论内容，支持markdown。']) }}
                </div>

                <p>
                    {{ Form::submit('提交', ['class' => 'am-btn am-btn-default', 'id'=>'store-comment']) }}
                </p>
            </fieldset>
            {!! Form::close() !!}
        @else
            <p>
                <a href="{{route('login')}}" class="am-btn am-btn-secondary am-btn-block">
                    <span class="am-icon-user"></span> 登录后发评论
                </a>
            </p>
        @endif
    </div>
@endsection
@section('scripts')
    <script src="/assets/vendor/highlight/highlight.min.js"></script>
    <script src="/assets/vendor/atwho/jquery.caret.min.js"></script>
    <script src="/assets/vendor/atwho/jquery.atwho.min.js"></script>
    <script src="/assets/vendor/jquery.hotkeys/jquery.jquery.hotkeys.js"></script>
    <script src="/assets/js/show.js"></script>
    @endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>Laravel Meetup</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="format-detection" content="telephone=no">
    <meta name="renderer" content="webkit">
    <meta http-equiv="Cache-Control" content="no-siteapp"/>
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <link rel="stylesheet" href="/assets/vendor/amazeui/css/amazeui.min.css"/>
    <link rel="stylesheet" href="/assets/css/common.css">
    @yield('stylesheets')
</head>

<body>
<header class="am-topbar am-topbar-fixed-top">
    <div class="am-container">
        <h1 class="am-topbar-brand">
            <a href="/">Meetup</a>
        </h1>

        <button class="am-topbar-btn am-topbar-toggle am-btn am-btn-sm am-btn-secondary am-show-sm-only"
                data-am-collapse="{target: '#collapse-head'}"><span class="am-sr-only">导航切换</span> <span
                    class="am-icon-bars"></span></button>

        <div class="am-collapse am-topbar-collapse" id="collapse-head">
            <ul class="am-nav am-nav-pills am-topbar-nav">
                <li><a href="{{route('issues.index')}}">活动</a></li>
                <li><a href="/about">关于</a></li>
            </ul>

            @if (Auth::guest())
                <div class="am-topbar-right">
                    <a href="{{route('login')}}" class="am-btn am-btn-secondary am-topbar-btn am-btn-sm">
                        <span class="am-icon-user"></span> Login
                    </a>
                </div>
                <div class="am-topbar-right">
                    <a href="{{route('register')}}" class="am-btn am-btn-primary am-topbar-btn am-btn-sm">
                        <span class="am-icon-pencil"></span> Sign Up
                    </a>
                </div>
            @else
                <div class="am-collapse am-topbar-collapse" id="topbar-collapse">
                    <ul class="am-nav am-nav-pills am-topbar-nav am-topbar-right admin-header-list">
                        <li class="am-dropdown" data-am-dropdown>
                            <a class="am-btn-secondary am-dropdown-toggle" data-am-dropdown-toggle href="javascript:;">
                                <span class="am-icon-user"></span> {{Auth::user()->name}}
                                <span class="am-icon-caret-down"></span>
                            </a>
                            <ul class="am-dropdown-content">
                                <li>
                                    <a href="{{ url('/logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                                        <span class="am-icon-power-off"></span> 退出
                                    </a>
                                    <form id="logout-form" action="{{ url('/logout') }}" method="POST" style="display: none;">
                                        {{ csrf_field() }}
                                    </form>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
            @endif
        </div>
    </div>
</header>
@include('shared._flash')
@yield('content')

<footer class="footer">
    <p class="am-padding-left">Copyright © 2017. Made With <i class="am-icon am-icon-heart"></i> By Aaron. All Rights
        Reserved.</p>
</footer>

<!--[if lt IE 9]>
<script src="http://libs.baidu.com/jquery/1.11.1/jquery.min.js"></script>
<script src="http://cdn.staticfile.org/modernizr/2.8.3/modernizr.js"></script>
<script src="/assets/vendor/amazeui/js/amazeui.ie8polyfill.min.js"></script>
<![endif]-->

<!--[if (gte IE 9)|!(IE)]><!-->
<script src="/assets/js/jquery.min.js"></script>
<!--<![endif]-->
<script src="/assets/vendor/amazeui/js/amazeui.min.js"></script>
<script src="/assets/js/laravel.js"></script>
<script src="/assets/js/common.js"></script>
@yield('scripts')
</body>
</html>

resources/views/shared/_comment.blade.php
<li class="am-comment">
    <img src="{{$comment->user->avatar()}}" alt="" class="am-comment-avatar" width="48" height="48">

    <div class="am-comment-main">
        <header class="am-comment-hd">
            <div class="am-comment-meta">
                <span class="am-comment-author">{{$comment->user->name}}</span>
                {{$comment->created_at->diffForHumans()}}
            </div>
        </header>
        <div class="am-comment-bd"><p>{!! markdown($comment->content) !!}</p></div>
    </div>
</li>

resources/views/shared/_flash.blade.php
@if (session('notice'))
    <div class="am-alert am-alert-success">
        <div class="am-container">
            {{ session('notice') }}
        </div>
    </div>
@endif

@if (session('alert'))
    <div class="am-alert am-alert-danger">
        <div class="am-container">
            {{ session('alert') }}
        </div>
    </div>
@endif

@if (count($errors) > 0)
    <div class="am-alert am-alert-danger">
        <div class="am-container">
            <h2>Oops~ There's something wrong!</h2>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    </div>
@endif

resources/views/shared/_issue_list.blade.php
<div class="am-container">
    <div data-am-widget="list_news" class="am-list-news am-list-news-default">
        <!--列表标题-->
        <div class="am-list-news-bd">
            <ul class="am-list">

                @foreach($issues as $issue)
                    <li class="am-g am-list-item-desced am-list-item-thumbed am-list-item-thumb-left">
                        <div class="am-u-sm-2 am-u-md-1 am-list-thumb">
                            <a href="{{route('issues.show', $issue->id)}}">
                                <img src="{{$issue->user->avatar()}}" alt=""/>
                            </a>
                        </div>

                        <div class="am-u-sm-7 am-u-md-9 am-list-main">
                            <h3 class="am-list-item-hd">
                                <a href="{{route('issues.show', $issue->id)}}" class="">{{$issue->title}}</a>
                            </h3>

                            <div class="am-list-item-text">
                                <span class="am-badge am-badge-secondary am-radius">read</span>
                                <span class="meta-data">{{$issue->user->name}}</span>
                                {{$issue->created_at->diffForHumans()}}
                            </div>
                        </div>
                        <div class="am-u-sm-3 am-u-md-2 issue-comment-count">
                            <span class="am-icon-comments"></span>
                            <a href="{{route('issues.show',$issue->id)}}">{{$issue->comments->count()}}</a>
                        </div>
                    </li>
                @endforeach

            </ul>
        </div>
    </div>
</div>

resources/views/welcome/about.blade.php
@extends('layouts.app')

@section('content')
    <div class="detail">
        <div class="am-g am-container">
            <div class="am-u-lg-12">
                <h1 class="detail-h1">About</h1>
            </div>
        </div>
    </div>
@endsection

resources/views/welcome/index.blade.php
@extends('layouts.app')

@section('content')

    <div class="get">
        <div class="am-g">
            <div class="am-u-lg-12">
                <h1 class="get-title">It's Party Time!<br>Drink Up!</h1>

                <p>到时聚聚、聊聊程序</p>

                <p>
                    <a href="{{route('issues.create')}}" class="am-btn am-btn-default am-btn-secondary">发布新活动</a>
                </p>
            </div>
        </div>
    </div>

    <div class="detail">
        <div class="am-g am-container">
            <div class="am-u-lg-12">
                <h1 class="detail-h1">最新的活动</h1>
            </div>
        </div>
    </div>

    @include('shared._issue_list')
@endsection